### ISSUE TITLE
the document -- the example

### ISSUE THREAD

**Issue by IamRoadRunner** [gophish/api-client-python#12]
hey man !
  I don't know how to use the api-client-python, and I read your document,
but, there is  always error message ,when I use the same code . It's better to write more.

**Comment by jordan-wright** [comment]
Hi there!

Thanks for reaching out. I'm afraid there isn't enough information here to really be actionable. 🙁 

If there are any specific examples or errors you are running into, let me know and I'll be happy to help troubleshoot. Thanks again for getting in touch!
