### ISSUE TITLE
Dependecies are outdated

### ISSUE THREAD

**Issue by MglMX** [gophish/api-client-python#26]
There are newer versions for dependencies that are required to install this package (appdirs, packaging, pyparsing and six).

Having newer version of these packages installed in the environment  causes a warning when trying to install gophish.

**Comment by mostafa-abdo** [comment]
Also for *python-dateutil*: `ERROR: gophish 0.4.0 has requirement python-dateutil==2.6.0, but you'll have python-dateutil 2.8.1 which is incompatible.`

**Comment by inlguy** [comment]
We have the same issue.

**Comment by emacstheviking** [comment]
This needs changing, newer versions of pip will not install, from the pip documentation:

> The most significant changes to the resolver are:
> It will reduce inconsistency: it will no longer install a combination of packages that is mutually inconsistent. In older versions of pip, it is possible for pip to install a package which does not satisfy the declared requirements of another installed package. For example, in pip 20.0, pip install "six<1.12"
> "virtualenv==20.0.2" does the wrong thing, “successfully” installing six==1.11, even though virtualenv==20.0.2 requires six>=1.12.0,<2 (defined here). The new resolver, instead, outright rejects installing anything if it gets that input.

I smell a lot of things breaking globally very soon. All for the sake of changing setup.py...

**Comment by jordan-wright** [comment]
Sorry for the delay, this was fixed in 0.5.1 which I just published.
