### ISSUE TITLE
Typo right here.

### ISSUE THREAD

**Issue by SwedishBotMafia** [gophish/api-client-python#8]
https://github.com/gophish/api-client-python/blob/ad4229c9c753be38caa69a5346aeb869bd42ab8e/gophish/api/api.py#L97

`if not respose.ok` should be `if not response.ok:`

**Comment by jordan-wright** [comment]
Sorry for the late reply to this! Great catch. I've merged #11 which addresses this. I'll get a new version pushed to PyPi ASAP.
