### ISSUE TITLE
SMTP Documentation is Wrong

### ISSUE THREAD

**Issue by ethack** [gophish/api-client-python#9]
The model attributes for SMTP profiles has the wrong documentation.  [This page](https://gophish.gitbooks.io/python-api-client/content/sending-profiles.html) has a list that I think is for Email Templates instead of SMTP profiles.

```
    id (int) The smtp ID
    name (str) The smtp name
    html (str) The smtp HTML
    text (str) The smtp HTML
    modified_date (optional: datetime.datetime) The scheduled time for smtp launch
    attachments (list(models.Attachment)) The optional email attachments
```

I think the real list should be based on [these lines](https://github.com/gophish/api-client-python/blob/master/gophish/models.py#L298-L304).  I'd be happy to update and submit a pull request, but I'm not sure where/if that's possible with Gitbook.

**Comment by jordan-wright** [comment]
Thanks for reporting this! I eventually need to find some time to sit down and work on the Python client and associated documentation to do some cleanup.

For now, I've gone ahead and synced the Gitbook content to Github, so pull requests should be possible 😄 

I've also fixed this particular documentation issue. Thanks again for reporting it!
